import { i18nConfig } from '@/i18nConfig';
import './globals.css';
import type { Metadata } from 'next';
import { Inter, Fira_Sans } from 'next/font/google';
import { ReactNode } from 'react';
import { dir } from 'i18next';

const inter = Inter({ subsets: ['latin'] });
const firaSans = Fira_Sans({
  subsets: ['latin', 'vietnamese'],
  weight: ['400', '500', '600', '700']
})

export const metadata: Metadata = {
  title: `minhquang231097's Portfolio | Next App`,
  description: 'Generated by Create Next App',
}

export function generateStaticParams() {
  return i18nConfig.locales.map(locale => ({ locale }));
}

export default function RootLayout({
  children,
  params: { locale }
}: {
  children: ReactNode;
  params: { locale: string };
}) {
  return (
    <html lang={locale} dir={dir(locale)}>
      <body className={firaSans.className}>{children}</body>
    </html>
  );
}
